### ISSUE TITLE
Configure authentication for InfluxDB

### ISSUE THREAD

**Issue by mdneuzerling** [mdneuzerling/starfleet#3]
The current configuration for connecting Prometheus to InfluxDB involves no authentication:

```yaml
remoteRead: 
  - url: "http://influxdb.default.svc.cluster.local:8086/api/v1/prom/read?db=prometheus"
remoteWrite: 
  - url: "http://influxdb.default.svc.cluster.local:8086/api/v1/prom/write?db=prometheus"
```

This leaves access to the database wide open. [It would be better to enable authentication to InfluxDB](https://docs.influxdata.com/influxdb/v1.8/administration/authentication_and_authorization/).

It is possible to add authentication to these URLs by giving a username and password as parameters, eg. "&u=username&p=password". However, this would involve putting the password in plaintext, so it's not much of an improvement. [Prometheus does not intend to support providing these values as secrets](https://github.com/prometheus/prometheus/issues/2357).

[The Prometheus Operator does seem to support basic authentication](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#remotereadspec) that would send a username as password as a header. However, if there's no SSL involved in this transmission, I'm not sure it's any better than the parameters.

I'm not sure yet if I need to connect Grafana to InfluxDB, but it also supports basic authentication:
```yaml
additionalDataSources: 
    - name: ...
      type: ...
      access: ...
      url: ...
      basicAuth: true
      basicAuthPassword: password
      basicAuthUser: username
```
